Post/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static 
from .views import  (
    Homepageview,
    Variousscamspageview,
    PostListView,
    PostUpdateView,
    PostDeleteView,
    PostDetailView,
    PostCreateView,
    CommentView,
    Aboutpageview,
    
 )



urlpatterns=[
    path('',PostListView.as_view(),name='home'),
    path('<int:pk>/',PostDetailView.as_view(),name='post_detail'),
    path('<int:pk>/edit',PostUpdateView.as_view(),name='post_edit'),
    path('<int:pk>/delete',PostDeleteView.as_view(),name='post_delete'),
    path('create/',PostCreateView.as_view(),name='post_create'),
    path('<int:pk>/comment',CommentView.as_view(),name='comment'),
    path('typesofscams/',Variousscamspageview.as_view(),name='typesofscams'),
    path('about/',Aboutpageview.as_view(),name='about'),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('',include('Post.urls')),
    path('Profile/',include('account.urls')),
]

Post/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.urls import reverse


# Create your models here.
class Post(models.Model):
    image=models.ImageField(default='default.jpg',upload_to='Scam_images')
    title=models.CharField(max_length=300)
    description=models.TextField() 
    created_at=models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)       


    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):       
      return reverse('post_detail', args=[str(self.id)])





class Comment(models.Model):
    scam=models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    comment=models.TextField(max_length=300)
    author=models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
   


    def __str__(self):
        return self.comment
          
          
    def get_absolute_url(self):        
        return reverse('scams_list')
    

templates/about.html
{% extends 'base.html' %}


{% block content %}


<div class="blog-header-container">
    <div class="blog-header">
      <div class="blog-article header-article">
        
         <div class="blog-big__title">About us</div> 
        
         <div class="blog-menu small-title date"></div>
      </div>
      <div class="blog-article">
       <div class="blog-detail">
        <span></span>
        <span></span>
       </div>
       <p>Welcome to our scam awareness website! We are dedicated to creating a safe online space where users can share their experiences, raise awareness about scams, and protect others from falling victim to fraudulent activities. Through our platform, users can sign up, log in, and contribute to the fight against scams by sharing their stories and insights</p>
       <a href="#">
       
        
        Swipe 
       </a>
      </div>
     </div>




     <div class="blog-header-container">
        <div class="blog-header">
          <div class="blog-article header-article">
            
                <div class="blog-big__title">Our Mission</div> 
            
           <div class="blog-menu small-title date"></div>
          </div>
          <div class="blog-article">
 
           <div class="blog-detail">
            <span></span>
            <span></span>
           </div>
           <p>Our mission is to empower individuals and communities to recognize, report, and prevent scams. We believe that by sharing personal experiences and knowledge, we can build a collective defense against deceptive practices. Through education, awareness, and collaboration, we strive to minimize the impact of scams on individuals, families, and businesses.</p>
           
          </div>
         </div>


         <div class="blog-header-container">
            <div class="blog-header">
              <div class="blog-article header-article">
                
                    <div class="blog-big__title">Join our Community</div> 
                
               <div class="blog-menu small-title date"></div>
              </div>
              <div class="blog-article">
            
               <div class="blog-detail">
                <span></span>
                <span></span>
               </div>
               <p>We invite you to become part of our scam awareness community. By signing up, sharing your stories, and engaging with other users, you are contributing to the fight against scams. Together, we can create a safer digital environment and protect vulnerable individuals from falling victim to fraudulent schemes.</p>
               
              </div>
             </div>
         </div>
         </div>
</div>


{% endblock content %}

templates/base.html
{%load static %}
{%load log %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ScamSlayers</title>
  <link href="{% static 'css/base.css' %}" rel="stylesheet">
  
</head>



<body>

<div class="blog">
  <div class="navbar">
    <div class="menu-icon">
      <div class="menu-line"></div>
      <div class="menu-line"></div>
      <div class="menu-line"></div>
    </div>
    <ul class="nav-items">
      <li><a href="{% url 'home'%}">Home</a></li>
      <li><a href="{% url 'about'%}">About</a></li>
      <li><a href="{%url 'typesofscams'%}">Types of Scams</a></li>
      
      {% if user.is_authenticated %}
      <li>Welcome,{{user.username}}</li>
      <li><a href="{% url 'post_create' %}" class="blog-menu">Create New Post</a></li>
      <li> <a href="{% url 'profile' user.pk%}" >Profile</a></li>
      <li><a href="{% url 'logout' %}" class="blog-menu">Logout</a></li>
      {% else %}
      <li><a class="blog-menu" href="{% url 'signup' %}">Sign Up</a></li>
      <li><a class="blog-menu" href="{% url 'login' %}">Log In</a></li>
    {% endif %}

      <li><a href="#">Contact</a></li>
   </ul> 
   
    
    
    <div class="close-btn">X</div>
  </div>
  
  

  <div class="blog-part is-menu">
   <a href="{% url 'home'%}" class="blog-menu">
    Home
    <svg fill="none" stroke="currentColor" stroke-width=".7" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-up-right" viewBox="0 0 24 24">
     <path d="M7 17L17 7M7 7h10v10" />
    </svg>
   </a>
   <a href="{%url 'typesofscams'%}" class="blog-menu">Types of Scams</a>

   {% if user.is_authenticated %}
      <h2>Welcome,{{user.username}}</h2>
      <a href="{% url 'post_create' %}" class="blog-menu">Create New Post</a>
      <a href="{% url 'logout' %}" class="blog-menu">Logout</a>
   {% else %}
      <a class="blog-menu" href="{% url 'signup' %}">Sign Up</a>
      <a class="blog-menu" href="{% url 'login' %}">Log In</a>
    {% endif %}
  {%if user.is_authenticated%}
   <a href="{% url 'about'%}" class="blog-menu mention">About</a>
   <a href="{% url 'profile' user.pk%}" class="blog-menu subscribe">Profile</a>
   {%endif%}
  </div>

  <div class="blog-header-container">
  {%block content%}
   
   {%endblock content%}
  </div>
  <div class="blog-part right-blog">
   <marquee width="100%" direction="left">
    <span>Protect Yourself from Scams!</span>
    <span>Be scam-savvy in the real world too!</span>
    <span>Arm yourself with knowledge and protect yourself from offline scams</span>
   </marquee>
   <div class="blog-right-title-container">
    <div class="blog-right-title">
     Featured Articles
    </div>
    <div class="blog-menu rounded">See All</div>
   </div>
   <div class="blog-right">
    <div class="blog-right-container">
     <div class="blog-title-date">
      <div class="blog-right-page">1</div>
      <div class="date">12.06.2021</div>
     </div>
     <div class="blog-right-page-title">Charles Ponzi: The Original Ponzi Scheme</div>
     <div class="blog-right-page-subtitle">Charles Ponzi gave his name to the now notorious term “Ponzi scheme.” His massive money scam is one of the most notable in history, and yet it began with something very small and simple: postage stamps</div>
    </div>
    <div class="blog-right-container">
     <div class="blog-title-date">
      <div class="blog-right-page">2</div>
      <div class="date">12.06.2021</div>
     </div>
     <div class="blog-right-page-title">Enron Scandal: The Fall  a Wall Street Darling</div>
     <div class="blog-right-page-subtitle"><a href="https://www.investopedia.com/updates/enron-scandal-summary/">The story of Enron Corp. depicts a company that reached dramatic heights only to face a dizzying fall</div></a>
    </div>
    <div class="blog-right-container">
     <div class="blog-title-date">
      <div class="blog-right-page">3</div>
      <div class="date">By David Marin</div>
     </div>
     <div class="blog-right-page-title"> The $64 Billion  Scam</div>
     <div class="blog-right-page-subtitle">
      <a href="https://s.yimg.com/ny/api/res/1.2/_w7vfnqVOP8RbX9tnHwvmw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTk2MDtoPTY0MjtjZj13ZWJw/https://media.zenfs.com/en/gobankingrates_644/91a9ba95f20416784e646de1b1f861a5">
        How Bernard Madoff Pulled Off The Biggest Ponzi Scheme....</div></a>
    </div>
    <div class="circle">
     <div class="circle-title">Leave Your Old Life Behind</div>
     <div class="circle-subtitle">Don't try to be like someone else, be yourself. Be secure with yourself.</div>
     <div class="circle-footer">Explore</div>
    </div>
   </div>
  </div>
 </div>

 <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/comment.html
{%load static%}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/comment.css' %}">
{% endblock %}


  <div class="comment-container">
    <h2 class="comment-title">Leave a Comment</h2>
    <form class="comment-form" method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="id_comment">Comment:</label>
    <input type="text" name="comment" maxlength="300" required="" id="id_comment">
      </div>
      <div class="form-group">
        <button type="submit" class="comment-button">Post Comment</button>
      </div>
    </form>
  </div>

templates/home.html
{% extends 'base.html' %}

{% load custom_filters %}

{% block content %}

{% for post in object_list %}
<div class="blog-header-container">
    <div class="blog-header">
      <div class="blog-article header-article">
        {% with word_index=forloop.counter0 %}
           {% with word=words|get_item:word_index|default:'' %}
            <div class="blog-big__title">{{ word }}</div> 
            {% endwith %}
        {% endwith %}
       <div class="blog-menu small-title date">{{ post.created_at|timesince }} ago</div>
      </div>
      <div class="blog-article">
       <img src="{{ post.image.url }}" alt="">
       <h2><span>{{ post.title }}</span></h2>
       <div class="blog-detail">
        <span>{{ post.author }}</span>
        <span></span>
       </div>
       <p>{{ post.description }}</p>
       <a href="{% url 'post_detail' post.pk %}">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-corner-down-right" viewBox="0 0 24 24">
         <path d="M15 10l5 5-5 5" />
         <path d="M4 4v7a4 4 0 004 4h12" />
        </svg>
        See More
       </a>
      </div>
     </div>
  </div>
    
{% endfor %}

{% endblock content %}

templates/post_create.html
{%load static%}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/signup.css' %}">
{% endblock %}

{% block content %}
<div class="signup-container">
  <title>Create Post</title>
  <h2 class="signup-title">Create Post</h2>
  <form class="signup-form" method="post" enctype="multipart/form-data" id="postForm">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_image">Image:</label>
      <input type="file" name="image" accept="image/*" id="id_image">
    </div>
    <div class="form-group">
      <label for="id_title">Title:</label>
      <input type="text" name="title" maxlength="300" required="" id="id_title">
    </div>
    <div class="signup-form">
      <label for="id_description">Description:</label>
      <textarea   name="description" cols="40" rows="10" required="" id="id_description"></textarea>
      <br>
      <br>
      <button type="submit" form="postForm">Create</button>
    </div>
    
  </form>
</div>
{% endblock content %}

templates/post_delete.html
<!-- templates/post_delete.html -->


{% block content %}
  <div class="confirmation-container">
    <h1>Are you sure?</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Delete</button>
    </form>
  </div>
{% endblock content %}

{% block styles %}
<style>
@import url("https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@1,400;1,500&family=Inter:wght@300;400;500;600&family=Space+Grotesk:wght@400;500;600;700&display=swap");

  .confirmation-container {
    max-width: 400px;
    margin: 0 auto;
    padding: 40px;
    border: 4px solid #100e0d;
    border-radius: 4px;
    font-family: "Space Grotesk", sans-serif;
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  h1 {
    font-family: "Space Grotesk", sans-serif;
    font-size: 28px;
    color: #333;
    text-align: center;
    margin-bottom: 20px;
  }

  form {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  form label {
    font-size: 16px;
    font-weight: bold;
    color: #333;
    margin-bottom: 10px;
  }

  form input[type="text"],
  form textarea {
    width: 100%;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    margin-bottom: 20px;
    resize: vertical;
  }

  form button[type="submit"] {
   font-family: "Space Grotesk", sans-serif;
  padding: 10px 16px;
  background-color: #3f3b3b;
  border: none;
  color: #fff;
  font-size: 16px;
  font-weight: 500;
  border-radius: 4px;
  cursor: pointer;
  transition: background-color 0.3s;
   
  }

  form button[type="submit"]:hover {
    background-color: #ff3232;
  }
</style>
{% endblock styles %}

templates/post_detail.html
{%extends 'base.html' %}
{% block content %}


<div class="blog-header">
  <div class="blog-article header-article">
   <div class="blog-big__title">Stay Skeptical</div>
   <div class="blog-menu small-title date">{{object.created_at|timesince}}</div>
  </div>
  <div class="blog-article">
   <img src="{{object.image.url}}" alt="">
   <h2> <span>{{object.title}}</span> </h2>
   <div class="blog-detail">
    <span> Posted by:{{object.author}}</span>
    <span></span>
    {% if can_edit %}
    <div> 
    <a href="{% url 'post_edit' object.pk %}">Edit</a>
    <a href="{% url 'post_delete' object.pk %}">Delete</a>
    </div>
    {% endif %}
   </div>
   <p>{{object.description}}</p>
   <div>
    <a href="{%url 'comment' object.pk %}">Add comment</a>
   </div>
   <h5>Post comments</h5>
   {% for comment in object.comments.all %}          
   <p>            
     <span class="font-weight-bold">              
       {{ comment.author }} &middot;            
     </span>            
     {{ comment }}          
   </p>        
   {% endfor %}   
  </div>
  
 
  
 </div>


 
 

{%endblock content %}

templates/post_edit.html
<!-- templates/post_edit.html -->


{% block content %}
<div class="form-container">
    <h1>Edit</h1>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-field">
        <label for="id_title">Title:</label>
        {{ form.title }}
      </div>
      <div class="form-field">
        <label for="id_description">Description:</label>
        {{ form.description }}
      </div>
      <div class="form-field">

 
        <label for="id_image">Change Image:</label>
      
        {{ form.image }}
      </div>
      <button type="submit">Update</button>
    </form>
  </div>
{% endblock content %}

{% block styles %}
<style>


  /* edit.css */

@import url("https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@1,400;1,500&family=Inter:wght@300;400;500;600&family=Space+Grotesk:wght@400;500;600;700&display=swap");

* {
  outline: none;
  box-sizing: border-box;
}

.form-container {
  max-width: 400px;
  margin: 0 auto;
  padding: 40px;
  border: 4px solid #100e0d;
  border-radius: 4px;
  font-family: "Inter", sans-serif;
}

.form-container h1 {
  color: #000;
  font-family: "Space Grotesk", sans-serif;
  font-size: 28px;
  font-weight: 600;
  margin-bottom: 20px;
}

.form-container form {
  display: flex;
  flex-direction: column;
}

.form-field {
  margin-bottom: 20px;
}

.form-field label {
  color: #000;
  font-family: "Space Grotesk", sans-serif;
  font-weight: 500;
  display: block;
  margin-bottom: 8px;
}

.form-field input[type="text"],
.form-field textarea {
  width: 100%;
  padding: 10px;
  border: 1px solid #94918f;
  border-radius: 4px;
  background-color: transparent;
  color: #000;
  font-size: 16px;
}

.form-field button{
  padding: 10px 16px;
  background-color: #121418;
  border: none;
  color: #fff;
  font-size: 16px;
  font-weight: 500;
  border-radius: 4px;
  cursor: pointer;
  transition: background-color 0.3s;
}

.form-field button:hover {
  background-color: #161419;
}

/* Responsive Styles */

@media (max-width: 768px) {
  .form-container {
    padding: 20px;
  }

  .form-container h1 {
    font-size: 24px;
  }

  .form-field input[type="text"],
  .form-field textarea {
    font-size: 14px;
  }
}

</style>
{% endblock styles %}

templates/profile_update.html
<form method="post" enctype="multipart/form-data">
    {%csrf_token%}
    {{form.as_p}} 
    <button type="submit">    
        Update
    </button>
</form>

templates/profile_view.html
{% load static %}

<html>
<head>
    <title>Profile</title>
    <link href="{% static 'css/profile.css' %}" rel="stylesheet"> 
</head>
<body>
    <div class="profile-container">
        <h2>Profile</h2>
        <div class="profile-image">
            <img src="{{ user.profile.image.url }}" alt="Profile Image">
        </div>
        <div class="profile-info">
            <label>Username:&nbsp;&nbsp;{{ user.username }}</label>
            
        </div>
        <div class="profile-info">
            <label>Bio:&nbsp;&nbsp; <span>{{ user.profile.bio }}</span></label>
            
        </div>
        <div class="profile-info">
            <label>Badge:&nbsp;&nbsp; <span class="badge">{{ user.profile.badge }}</span></label>

        </div>
        <a href="{% url 'profile_update' object.pk %}"<button class="edit-button">Edit</button></a>
    </div>
</body>
</html>

templates/typesofscams.html
{% extends 'base.html' %}


{% block content %}


<div class="blog-header-container">
    <div class="blog-header">
      <div class="blog-article header-article">
        
            <div class="blog-big__title">1</div> 
        
       <div class="blog-menu small-title date"></div>
      </div>
      <div class="blog-article">
       <img src="https://www.shutterstock.com/image-vector/ponzi-scheme-vector-illustration-business-600w-1624207702.jpg" alt="Ponzi">
       <h2><span>Ponzi Schemes</span></h2>
       <div class="blog-detail">
        <span></span>
        <span></span>
       </div>
       <p>Ponzi schemes involve promising high returns on investments by using funds from new investors to pay off older ones. One notorious example is the Satyam Computer Services scam, where the company's founder manipulated financial statements to inflate the company's profits.</p>
       
      </div>
     </div>




     <div class="blog-header">
        <div class="blog-article header-article">
          
              <div class="blog-big__title">2</div> 
          
         <div class="blog-menu small-title date"></div>
        </div>
        <div class="blog-article">
         <img src="https://www.shutterstock.com/image-vector/cyber-thief-hacker-wearing-man-600w-618026255.jpg" alt="fraud pic">
         <h2><span>Online Fraud</span></h2>
         <div class="blog-detail">
          <span></span>
          <span></span>
         </div>
         <p> With the rise of the internet and digital transactions, various online scams have emerged. These include phishing, where scammers impersonate legitimate entities to obtain personal information, and online shopping fraud, where people are tricked into paying for products or services that are never delivered.</p>
         
        </div>
       </div>




       <div class="blog-header">
        <div class="blog-article header-article">
          
              <div class="blog-big__title">3</div> 
          
         <div class="blog-menu small-title date"></div>
        </div>
        <div class="blog-article">
         <img src="https://www.shutterstock.com/image-vector/employment-scam-neon-light-icon-600w-1576002868.jpg" alt="">
         <h2><span>Job Scams</span></h2>
         <div class="blog-detail">
          <span></span>
          <span></span>
         </div>
         <p>Job scams involve fraudulent individuals or organizations promising lucrative employment opportunities in exchange for upfront fees or personal information. Victims often end up losing money and providing sensitive data that can be misused</p>
         
        </div>
       </div>






       <div class="blog-header">
        <div class="blog-article header-article">
          
              <div class="blog-big__title">4</div> 
          
         <div class="blog-menu small-title date"></div>
        </div>
        <div class="blog-article">
         <img src="https://www.shutterstock.com/image-vector/mobile-scam-alert-illustration-phone-260nw-2271916327.jpg" alt="">
         <h2><span>Lottery Scams</span></h2>
         <div class="blog-detail">
          <span></span>
          <span></span>
         </div>
         <p>Scammers contact unsuspecting individuals, claiming they have won a lottery or prize and ask for a processing fee or personal information to release the winnings. The victims are often left empty-handed after paying the fees or providing their details.</p>
         
        </div>
       </div>





       <div class="blog-header">
        <div class="blog-article header-article">
          
              <div class="blog-big__title">5</div> 
          
         <div class="blog-menu small-title date"></div>
        </div>
        <div class="blog-article">
         <img src="https://www.shutterstock.com/image-vector/internet-fraud-hacker-behind-laptop-260nw-1822520654.jpg" alt="">
         <h2><span>Bank-related Scams</span></h2>
         <div class="blog-detail">
          <span></span>
          <span></span>
         </div>
         <p>Scammers may impersonate bank officials and contact individuals, requesting sensitive banking information or OTP (One-Time Password) details. They use this information to gain unauthorized access to bank accounts and carry out fraudulent transactions.</p>
         
        </div>
       </div>


       <div class="blog-header">
        <div class="blog-article header-article">
          
              <div class="blog-big__title">6</div> 
          
         <div class="blog-menu small-title date"></div>
        </div>
        <div class="blog-article">
         <img src="https://www.shutterstock.com/image-illustration/real-estate-scam-city-depicting-260nw-1424931875.jpg" alt="">
         <h2><span>Real Estate Scams</span></h2>
         <div class="blog-detail">
          <span></span>
          <span></span>
         </div>
         <p>In the real estate sector, scams can involve fraudulent property sales, illegal land grabbing, or selling properties with false documents. Victims may end up losing their investments or face legal complications.</p>
         
        </div>
       </div>


       <div class="blog-header">
        <div class="blog-article header-article">
          
              <div class="blog-big__title">7</div> 
          
         <div class="blog-menu small-title date"></div>
        </div>
        <div class="blog-article">
         <img src="https://www.shutterstock.com/shutterstock/photos/1335564905/display_1500/stock-photo-robocalls-word-cloud-on-blue-background-1335564905.jpg" alt="">
         <h2><span>Mobile/Telecom Scams</span></h2>
         <div class="blog-detail">
          <span></span>
          <span></span>
         </div>
         <p>Scams related to mobile phones and telecom services include fake calls or messages claiming to offer prizes or promotions. Scammers trick people into providing personal information or subscribing to costly services unknowingly.</p>
         
        </div>
       </div>


       <div class="blog-header">
        <div class="blog-article header-article">
          
              <div class="blog-big__title">8</div> 
          
         <div class="blog-menu small-title date"></div>
        </div>
        <div class="blog-article">
         <img src="https://www.shutterstock.com/image-vector/ponzi-scheme-fraud-type-multi-260nw-1727702725.jpg" alt="">
         <h2><span>Multi-level Marketing (MLM) Scams</span></h2>
         <div class="blog-detail">
          <span></span>
          <span></span>
         </div>
         <p>MLM scams often operate as pyramid schemes, where participants are promised high returns by recruiting others into the scheme. These schemes are often unsustainable and rely on constant recruitment to sustain payouts.</p>
         
        </div>
       </div>
  </div>
    

{% endblock content %}